---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: servers

- name: Delete instances
  os_server:
    name: "{{ item.name }}"
    cloud: openstack
    state: absent
  loop: "{{ servers.openstack_servers }}"
   
